scenario: v2v-emergencyVehicleAlert-nrv2x
sim_time_s: 30
rng_run: 1
sumo_gui: 0
sumo_updates: 0.01
penetrationRate: 0.7
base_args: []

sweep_points:
  - id: txPower_23
    txPower: 23
    mcs: 14
    enableSensing: false
    slThresPsschRsrp: -128
    enableChannelRandomness: false
    channelUpdatePeriod: 500
  - id: txPower_18
    txPower: 18
    mcs: 14
    enableSensing: false
    slThresPsschRsrp: -128
    enableChannelRandomness: false
    channelUpdatePeriod: 500
  - id: txPower_14
    txPower: 14
    mcs: 14
    enableSensing: false
    slThresPsschRsrp: -128
    enableChannelRandomness: false
    channelUpdatePeriod: 500
  - id: txPower_10
    txPower: 10
    mcs: 14
    enableSensing: false
    slThresPsschRsrp: -128
    enableChannelRandomness: false
    channelUpdatePeriod: 500
  - id: txPower_6
    txPower: 6
    mcs: 14
    enableSensing: false
    slThresPsschRsrp: -128
    enableChannelRandomness: false
    channelUpdatePeriod: 500
  - id: txPower_0
    txPower: 0
    mcs: 14
    enableSensing: false
    slThresPsschRsrp: -128
    enableChannelRandomness: false
    channelUpdatePeriod: 500
  - id: txPower_-10
    txPower: -10
    mcs: 14
    enableSensing: false
    slThresPsschRsrp: -128
    enableChannelRandomness: false
    channelUpdatePeriod: 500
  - id: txPower_-20
    txPower: -20
    mcs: 14
    enableSensing: false
    slThresPsschRsrp: -128
    enableChannelRandomness: false
    channelUpdatePeriod: 500
